In [2]:
import requests

In [3]:
+URL="https://stephen-king-api.onrender.com/api/books"
res=requests.get(URL)

In [4]:
json_data=res.json()

In [5]:
import pandas as pd

df=pd.json_normalize(json_data["data"])

In [15]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [22]:
# Web Scraping

import requests

URL="https://www.scrapethissite.com/pages/simple/"
res=requests.get(URL)

print(res.status_code)

200

In [29]:
if res.status_code==200:
    print(res.headers)

with open("scrape_data/data1.html","w",encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Thu, 19 Mar 2026 08:45:24 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=AOTvMuAtgjubl0GhABA1CpPR6iB%2FzGMKz3L0fYHKQ%2BE%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1773909923"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=AOTvMuAtgjubl0GhABA1CpPR6iB%2FzGMKz3L0fYHKQ%2BE%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1773909923"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9deb335e384111ac-MRS', 'alt-svc': 'h3=":443"; ma=86400'}

In [39]:
# Beautifulsoup
from bs4 import BeautifulSoup

with open("scrape_data/data1.html","r") as f:
    html_content=f.read()

soup=BeautifulSoup(html_content,"lxml")

In [90]:
all_h3=soup.find_all("h3")

for h3 in all_h3:
    name=h3.get_text(strip=True)
    #print(h3.find_parent("div")["class"])

    population=h3.find_next("div").select("span.country-population")[0].get_text(strip=True)

In [76]:
import pandas as pd

df=pd.DataFrame(all_countries,columns=["Name","Population"])
df

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [78]:
df.to_csv("cleaned_data/data.csv",index=False)

# Web Scraping Activity

## From quotes, extract all quotes and authors from all pages with the life tag.

In [3]:
import requests
from bs4 import BeautifulSoup

# Fetch data and store it

page_count=1

while True:
    URL=f"http://quotes.toscrape.com/page/{page_count}/"
    res=requests.get(URL)

    soup=BeautifulSoup(res.text,"lxml")
    quotes=soup.select("div.quote")

    if not quotes:
        print("No valid pages anymore..")
        break

    with open(f"scrape_data/quotes{page_count}.html","w",encoding="utf-8") as f:
        f.write(res.text)
        print(f"Downloaded data from page{page_count}.")
    page_count+=1

ConnectionError: HTTPConnectionPool(host='quotes.toscrape.com', port=80): Max retries exceeded with url: /page/1/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000265BA195400>: Failed to resolve 'quotes.toscrape.com' ([Errno 11001] getaddrinfo failed)"))

In [4]:
# Extract useful information

life_quotes=[]
for page in range(1,11):
    with open(f"scrape_data/quotes{page}.html","r",encoding="utf-8") as f:
        html_content=f.read()
    soup=BeautifulSoup(html_content,"lxml")
    all_quotes=soup.select("div.quote")
    for q in all_quotes:
        all_tags=[]

        for tag in q.select(".tags .tag"):
            all_tags.append(tag.get_text())
        if "life" in all_tags:
            text=q.select_one("span.text").get_text()
            author=q.select_one("small.author").get_text()
            life_quotes.append([text,author])
life_quotes

[['“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
  'Albert Einstein'],
 ['“It is better to be hated for what you are than to be loved for what you are not.”',
  'André Gide'],
 ["“This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.”",
  'Marilyn Monroe'],
 ['“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”',
  'Douglas Adams'],
 ['“Good friends, good books, and a sleepy conscience: this is the ideal life.”',
  'Mark Twain'],
 ['“Life is what happens to us while we are making other plans.”',
  'Allen Saunders'],
 ['“Today you are You, that is truer than true. There is no one alive who is Youer than You.”',
  'Dr. Seuss'],
 ['“Life is like riding a bicycle. To keep your balance, you must keep moving.”',
  'Albert Einstein'],
 ["“Life isn't about finding yourself. Life is about creating yourself.”",
  'George Bernard Shaw'],
 ['“Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.”',
  'Ralph Waldo Emerson'],
 ['“The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.”',
  'Mark Twain'],
 ["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”",
  'Jimi Hendrix'],
 ['“But better to get hurt by the truth than comforted with a lie.”',
  'Khaled Hosseini']]

In [5]:
import pandas as pd
df=pd.DataFrame(life_quotes,columns=["Quote","Author"])
df

                                                Quote               Author
0   “There are only two ways to live your life. On...      Albert Einstein
1   “It is better to be hated for what you are tha...           André Gide
2   “This life is what you make it. No matter what...       Marilyn Monroe
3   “I may not have gone where I intended to go, b...        Douglas Adams
4   “Good friends, good books, and a sleepy consci...           Mark Twain
5   “Life is what happens to us while we are makin...       Allen Saunders
6   “Today you are You, that is truer than true. T...            Dr. Seuss
7   “Life is like riding a bicycle. To keep your b...      Albert Einstein
8   “Life isn't about finding yourself. Life is ab...  George Bernard Shaw
9   “Finish each day and be done with it. You have...  Ralph Waldo Emerson
10  “The fear of death follows from the fear of li...           Mark Twain
11  “I'm the one that's got to die when it's time ...         Jimi Hendrix
12  “But better to get hurt by the truth than comf...      Khaled Hosseini

In [23]:
df.to_csv("cleaned_data/data1.csv",index=False)